parameters:
    hackzilla.password_generator.computer.length: 12

    hackzilla.password_generator.human.word_list: /usr/share/dict/words
    hackzilla.password_generator.human.word_separator: '-'
    hackzilla.password_generator.human.word_count: 3
    hackzilla.password_generator.human.min_word_length: 5
    hackzilla.password_generator.human.max_word_length: 10

    hackzilla.password_generator.hybrid.segment_count: 4
    hackzilla.password_generator.hybrid.segment_length: 3
    hackzilla.password_generator.hybrid.segment_separator: '-'

services:
    Hackzilla\PasswordGenerator\Generator\RequirementPasswordGenerator:
        public: true

    Hackzilla\PasswordGenerator\Generator\DummyPasswordGenerator:
        public: true

    Hackzilla\PasswordGenerator\Generator\ComputerPasswordGenerator:
        public: true
        calls:
          - [setLength, ["%hackzilla.password_generator.computer.length%"]]

    Hackzilla\PasswordGenerator\Generator\HumanPasswordGenerator:
        public: true
        calls:
          - [setWordCount, ["%hackzilla.password_generator.human.word_count%"]]
          - [setMinWordLength, ["%hackzilla.password_generator.human.min_word_length%"]]
          - [setMaxWordLength, ["%hackzilla.password_generator.human.max_word_length%"]]
          - [setWordSeparator, ["%hackzilla.password_generator.human.word_separator%"]]
          - [setWordList, ["%hackzilla.password_generator.human.word_list%"]]

    Hackzilla\PasswordGenerator\Generator\HybridPasswordGenerator:
        public: true
        calls:
          - [setSegmentCount, ["%hackzilla.password_generator.hybrid.segment_count%"]]
          - [setSegmentLength, ["%hackzilla.password_generator.hybrid.segment_length%"]]
          - [setSegmentSeparator, ["%hackzilla.password_generator.hybrid.segment_separator%"]]

    Hackzilla\Bundle\PasswordGeneratorBundle\Form\Type\OptionType:
        tags:
            - { name: form.type }

    Hackzilla\Bundle\PasswordGeneratorBundle\Controller\GeneratorController:
      public: true
      tags: ['controller.service_arguments']
      arguments:
        - '@Hackzilla\PasswordGenerator\Generator\HumanPasswordGenerator'
        - '@Hackzilla\PasswordGenerator\Generator\HybridPasswordGenerator'
        - '@Hackzilla\PasswordGenerator\Generator\ComputerPasswordGenerator'
        - '@Hackzilla\PasswordGenerator\Generator\RequirementPasswordGenerator'
        - '@Hackzilla\PasswordGenerator\Generator\DummyPasswordGenerator'
      calls:
        - [setContainer, ['@service_container']]
