dist: trusty

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: CS_FIXER=run
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.2
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.2
      env: SYMFONY_VERSION="4.0.*"
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION="4@dev"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit friendsofphp/php-cs-fixer --no-update
  - composer global update --prefer-dist --no-interaction
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - make test

after_success:
  - php vendor/bin/coveralls -c .coveralls.yml -v
